name: Build & Release APKs

on:
  push:
    tags:
      - "v*"

env:
  KEYSTORE_FILE: /tmp/keystore.jks
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      # 1. Check out the code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Decode keystore from secret

      - name: Decode keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > /tmp/keystore.jks


      # 4. Make gradlew executable

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      # 5. Build split APKs (arm64-v8a & armeabi-v7a)

      - name: Build release APKs
        run: ./gradlew clean assembleRelease

      # 6. Upload signed APKs to GitHub Release
      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app/build/outputs/apk/release/*arm64-v8a*.apk
            app/build/outputs/apk/release/*armeabi-v7a*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

